### ISSUE TITLE
Use Hydra's Compose API and Trainer.add_argparse_args

### ISSUE THREAD

**Issue by yukw777** [yukw777/leela-zero-pytorch#6]
Use Hydra's Compose API and `Trainer.add_argparse_args()` so that we can fully take advantage of PyTorchLightning's trainer without additional code.

**Comment by yukw777** [comment]
Maybe wait for this to go in: https://github.com/PyTorchLightning/pytorch-lightning/pull/1417

**Comment by reactivetype** [comment]
Can you elaborate on the benefits with a simple example?

**Comment by yukw777** [comment]
@reactivetype could you elaborate more? benefits of what?
